import { ProductEditor } from './components/ProductEditor';
import { getRotatedBoundingBox } from './utils/boundingBox';
import { useMemo, useState } from 'react';
import { ObjectPropertiesPanel } from './components/ObjectPropertiesPanel';
import { Scene3D } from './components/Scene3D';
import { Sidebar } from './components/Sidebar';
import { StatusPanel } from './components/StatusPanel';
import { MB5_CONTAINER, STARTER_OBJECTS } from './data/skus';
import type { OrientationOptimizationResult, PackingObject, PackingObjectType, TransformMode } from './types';
import { validateFit } from './utils/fitValidation';
import { calculateBestPacking as calculateGridPacking, findBestOrientation } from './utils/packingCalculator';

const COLORS = ['#2f80ed', '#00a878', '#f2994a', '#9b51e0', '#eb5757', '#2d9cdb'];
const DEFAULT_STAGING_POSITION = {
  x: 0,
  y: 0,
  z: 0,
};

const createPackingObject = (type: PackingObjectType, index: number): PackingObject => {
  const baseSize = type === 'cube' ? 250 : 320;
  const height = type === 'cylinder' ? 360 : type === 'cube' ? 250 : 220;

  return {
    id: `${type}-${crypto.randomUUID()}`,
    type,
    name: `${type.charAt(0).toUpperCase()}${type.slice(1)} ${index + 1}`,
    dimensions: {
      width: baseSize,
      depth: type === 'cube' || type === 'cylinder' ? baseSize : 260,
      height,
    },
    weightKg: 50,
    position: { ...DEFAULT_STAGING_POSITION, z: height / 2 },
    rotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    color: COLORS[index % COLORS.length],
  };
};

export default function App() {
  const [editor, setEditor] = useState<{ product: PackingObject | null } | null>(null);
  const [objects, setObjects] = useState<PackingObject[]>(STARTER_OBJECTS);
  const [selectedObjectId, setSelectedObjectId] = useState<string | null>(STARTER_OBJECTS[0]?.id ?? null);
  const [fillSpacingMm, setFillSpacingMm] = useState(0);
  const [transformMode, setTransformMode] = useState<TransformMode>('translate');
  const [previewObjects, setPreviewObjects] = useState<PackingObject[] | null>(null);
  const [lastPackingResult, setLastPackingResult] = useState<ReturnType<typeof calculateGridPacking> | null>(
    null,
  );
  const [orientationResult, setOrientationResult] = useState<OrientationOptimizationResult | null>(null);

  const selectedObject = objects.find((object) => object.id === selectedObjectId) ?? null;

  const validation = useMemo(() => validateFit(previewObjects ?? objects, MB5_CONTAINER), [objects, previewObjects]);

  const clearDerivedResults = () => {
    setPreviewObjects(null);
    setLastPackingResult(null);
    setOrientationResult(null);
  };

  const selectObject = (id: string | null) => {
    if (id === selectedObjectId || (previewObjects && id === null)) return;
    setSelectedObjectId(id);
    clearDerivedResults();
  };

  const changeFillSpacing = (spacingMm: number) => {
    setFillSpacingMm(spacingMm);
    clearDerivedResults();
  };

  const addObject = (type: PackingObjectType) => {
    const object = createPackingObject(type, objects.length);
    setObjects((currentObjects) => [...currentObjects, object]);
    setSelectedObjectId(object.id);
    clearDerivedResults();
  };

  const updateObject = (updatedObject: PackingObject) => {
    setObjects((currentObjects) =>
      currentObjects.map((object) => (object.id === updatedObject.id ? updatedObject : object)),
    );
    clearDerivedResults();
  };

  const deleteObject = (id: string) => {
    setObjects((currentObjects) => currentObjects.filter((object) => object.id !== id));
    setSelectedObjectId(null);
    clearDerivedResults();
  };

  const clearAutoFill = () => {
    setObjects((currentObjects) => currentObjects.filter((object) => !object.isAutoGenerated));
    clearDerivedResults();
  };

  const findBestObjectOrientation = () => {
    if (!selectedObject) {
      return;
    }

    const result = findBestOrientation(MB5_CONTAINER, selectedObject, fillSpacingMm);

    if (!result) {
      return;
    }

    const oriented = { ...selectedObject, rotation: result.rotation };
    const updated = { ...oriented, position: { x: 0, y: 0, z: getRotatedBoundingBox(oriented).height / 2 } };
    setObjects(current => current.map(object => object.id === updated.id ? updated : object));
    setPreviewObjects([updated]);
    setOrientationResult(result);
    setLastPackingResult(result.packingResult);
  };

  const fillContainer = () => {
    if (!selectedObject) {
      return;
    }

    const templateObject = selectedObject;

    const packingResult = calculateGridPacking(MB5_CONTAINER, templateObject, fillSpacingMm);

    const [templatePosition, ...clonePositions] = packingResult.positions;
    const clones = clonePositions.map((position, index) => ({
      ...templateObject,
      id: `${templateObject.id}-auto-${index + 1}`,
      name: `${templateObject.name} auto ${index + 1}`,
      position,
      isAutoGenerated: true,
      sourceObjectId: templateObject.id,
    }));
    const updatedTemplate = templatePosition
      ? { ...templateObject, position: templatePosition, isAutoGenerated: false, sourceObjectId: undefined }
      : templateObject;

    setPreviewObjects(templatePosition ? [updatedTemplate, ...clones] : []);
    setSelectedObjectId(templateObject.id);
    setLastPackingResult(packingResult);
    setOrientationResult(null);
  };

  if (editor) return <ProductEditor product={editor.product} onClose={() => setEditor(null)} onSave={product => {
    const bounds = getRotatedBoundingBox(product);
    const updated = { ...product, position: { x: 0, y: 0, z: bounds.height / 2 }, isAutoGenerated: false, sourceObjectId: undefined };
    setObjects(current => [...current.filter(object => object.id !== updated.id && object.sourceObjectId !== updated.id), updated]);
    setSelectedObjectId(updated.id);
    clearDerivedResults();
    setPreviewObjects([updated]);
    setEditor(null);
  }} />;

  return (
    <main className="app-shell">
      <Sidebar onAddObject={addObject} onCreateProduct={() => setEditor({ product: null })} onEditProduct={selectedObject ? () => setEditor({ product: selectedObject }) : undefined} objects={objects.filter(object => !object.isAutoGenerated)} selectedObjectId={selectedObjectId} onSelectObject={selectObject} />
      <section className="workspace" aria-label="3D packing workspace">
        <Scene3D
          objects={previewObjects ?? objects}
          selectedObjectId={selectedObjectId}
          transformMode={transformMode}
          onSelectObject={id => { const clicked = previewObjects?.find(object => object.id === id); selectObject(clicked?.sourceObjectId ?? id); }}
          onUpdateObject={updateObject}
        />
        <StatusPanel validation={validation} />
      </section>
      <ObjectPropertiesPanel
        selectedObject={selectedObject}
        fillSpacingMm={fillSpacingMm}
        lastPackingResult={lastPackingResult}
        orientationResult={orientationResult}
        transformMode={transformMode}
        onTransformModeChange={setTransformMode}
        onFillSpacingChange={changeFillSpacing}
        onFillContainer={fillContainer}
        onFindBestOrientation={findBestObjectOrientation}
        onClearAutoFill={clearAutoFill}
        onUpdateObject={updateObject}
        onDeleteObject={deleteObject}
      />
    </main>
  );
}
